// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCplGD1Pgqf-3jrlW9emNzoNvmPRJ6mEd8',
    appId: '1:907935480133:web:81b569f16c1133c4aea62c',
    messagingSenderId: '907935480133',
    projectId: 'flutter-home-work-552ce',
    authDomain: 'flutter-home-work-552ce.firebaseapp.com',
    storageBucket: 'flutter-home-work-552ce.firebasestorage.app',
    measurementId: 'G-804MVNX8XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPIbzK98b0cCaY4nHmAxSMf2kwLQuBQ4U',
    appId: '1:907935480133:android:f71902091ae04de6aea62c',
    messagingSenderId: '907935480133',
    projectId: 'flutter-home-work-552ce',
    storageBucket: 'flutter-home-work-552ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzIfp5HmzAhik6OlexmnRj1su3iql7rGA',
    appId: '1:907935480133:ios:1f99ac2debaa27f4aea62c',
    messagingSenderId: '907935480133',
    projectId: 'flutter-home-work-552ce',
    storageBucket: 'flutter-home-work-552ce.firebasestorage.app',
    iosBundleId: 'com.example.homeWork',
  );
}
