// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('WEB_API_KEY'),
    appId: const String.fromEnvironment('WEB_APP_ID'),
    messagingSenderId: const String.fromEnvironment('MESSAGING_SENDER_ID'),
    projectId: const String.fromEnvironment('PROJECT_ID'),
    authDomain: const String.fromEnvironment('AUTH_DOMAIN'),
    storageBucket: const String.fromEnvironment('STORAGE_BUCKET'),
    measurementId: const String.fromEnvironment('WEB_MEASUREMENT_ID'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('ANDROID_API_KEY'),
    appId: const String.fromEnvironment('ANDROID_APP_ID'),
    messagingSenderId: const String.fromEnvironment('MESSAGING_SENDER_ID'),
    projectId: const String.fromEnvironment('PROJECT_ID'),
    storageBucket: const String.fromEnvironment('STORAGE_BUCKET'),
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('IOS_API_KEY'),
    appId: const String.fromEnvironment('IOS_APP_ID'),
    messagingSenderId: const String.fromEnvironment('MESSAGING_SENDER_ID'),
    projectId: const String.fromEnvironment('PROJECT_ID'),
    storageBucket: const String.fromEnvironment('STORAGE_BUCKET'),
    androidClientId: const String.fromEnvironment('ANDROID_CLIENT_ID'),
    iosClientId: const String.fromEnvironment('IOS_CLIENT_ID'),
    iosBundleId: const String.fromEnvironment('IOS_BUNDLE_ID'),
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('MACOS_API_KEY'),
    appId: const String.fromEnvironment('MACOS_APP_ID'),
    messagingSenderId: const String.fromEnvironment('MESSAGING_SENDER_ID'),
    projectId: const String.fromEnvironment('PROJECT_ID'),
    storageBucket: const String.fromEnvironment('STORAGE_BUCKET'),
    androidClientId: const String.fromEnvironment('ANDROID_CLIENT_ID'),
    iosClientId: const String.fromEnvironment('MACOS_CLIENT_ID'),
    iosBundleId: const String.fromEnvironment('MACOS_BUNDLE_ID'),
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('WINDOWS_API_KEY'),
    appId: const String.fromEnvironment('WINDOWS_APP_ID'),
    messagingSenderId: const String.fromEnvironment('MESSAGING_SENDER_ID'),
    projectId: const String.fromEnvironment('PROJECT_ID'),
    authDomain: const String.fromEnvironment('AUTH_DOMAIN'),
    storageBucket: const String.fromEnvironment('STORAGE_BUCKET'),
    measurementId: const String.fromEnvironment('WINDOWS_MEASUREMENT_ID'),
  );
}
